#!/usr/bin/env bash
# script that configures a server to ensure that Nginx must be running
# and listening on port 80 of all the server’s active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
