#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.
# The exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# In list format

apache-log="apache-access.log"
awk -F' ' '{ print $1, $9}' $apache-log | sort | uniq -c|sort -nr
