#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.

apache-log="apache-access.log"
awk -F' ' '{ print $1, $9}' $apache-log | sort | uniq -c|sort -nr
